### ISSUE TITLE
[feature request] server icon size variable

### ISSUE THREAD

**Issue by NeonLightning** [squee666/Discord-Themes#2]
i'll admit i use quiet with other themes to get it how i like it. but the one thing i don't like that quiet adds is it changes the server icon size to a huge size.
having some sorta variable accessible would be helpful.

**Comment by squee666** [comment]
hello can you be more specific , Server Icons (guilds) is unchanged from stock discord and so is Server Banners if that's what you meant.

the only modification i have really done in that area is mkaing dm icon static and discord servers scroll without overlapping it

edit*

I found ".wrapper-28eC3z , .svg-2zuE5p{width: 48px !important;height: 48px !important;}" in code which was forcing guild icons to stay stock size, so if you are using zoom level inside discord it would stay 

I didnt notice any difference though in server icon sizes

But if its overriding another theme because of the above code it shouldnt anymore

**Comment by NeonLightning** [comment]
hrm still doing it. i think yes it means the guilds. with quiet off my icons are spaced perfectly and sized nicely at 32 but for some reason when i enable it they all go back to stock size(only when when active or when i mouseover them.) still even after relaunching and reloading the theme.css

**Comment by NeonLightning** [comment]
scratch that this time i just had to switch between on and off to make them all show as stock size again. but here's an example. i appreciate your time. it's probably something conflicting with something else i'm using. possibly the horizontal guilds
![image](https://user-images.githubusercontent.com/2992888/206882685-db85b387-13a5-4f29-8b71-1537cbc1d7fd.png)
![image](https://user-images.githubusercontent.com/2992888/206882699-d53456d6-8702-4a9a-b810-898e78e5aed4.png)

**Comment by NeonLightning** [comment]
odd all the sudden it's not doing it so. well whatever seems good now lol
